language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_case;" -U postgres
  - psql -c "CREATE USER migrator WITH PASSWORD 'postgres';" -U postgres